version: '3.1'

services:
  api:
    build: api-gateway
    command: "python app.py"
    ports:
      - 5000:5000
    depends_on:
      - flask_service
      - go_service

  flask_service:
    build: flask-service
    command: "python app.py"

  go_lb:
    image: dockercloud/haproxy
    links:
      - go_service
      - flask_service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  go_service:
    build: go-service
